"use client";

import { useEffect, useMemo, useState } from "react";

type Metrics = { users: number; rooms: number; activeRooms: number; players: number; aiUses: number; aiEstimatedCostUsd: string };
type Lists = Record<keyof Metrics, Array<Record<string, unknown>>>;
type Filter = keyof Metrics;
const labels: Record<Filter, string> = { users: "Users", rooms: "Rooms", activeRooms: "Active rooms", players: "Players", aiUses: "AI uses", aiEstimatedCostUsd: "Estimated AI cost" };
function formatValue(value: unknown, key: string) { if (value === null || value === undefined) return "—"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (["createdAt", "updatedAt", "joinedAt", "windowStart", "subscriptionExpiresAt"].includes(key)) return new Date(String(value)).toLocaleString(); return String(value); }
function UserTable({ rows, save }: { rows: Array<Record<string, unknown>>; save: (row: Record<string, unknown>) => Promise<void> }) { if (!rows.length) return <p className="admin-empty">No users yet.</p>; return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>email</th><th>name</th><th>role</th><th>plan</th><th>status</th><th>expires</th><th>save</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}><td>{formatValue(row.email, "email")}</td><td>{formatValue(row.displayName, "displayName")}</td><td><select defaultValue={String(row.role)} onChange={(event) => { row.role = event.target.value; }}><option value="user">user</option><option value="admin">admin</option></select></td><td><select defaultValue={String(row.plan ?? "free")} onChange={(event) => { row.plan = event.target.value; }}><option value="free">free</option><option value="premium">premium</option></select></td><td><select defaultValue={String(row.subscriptionStatus ?? "inactive")} onChange={(event) => { row.subscriptionStatus = event.target.value; }}><option value="inactive">inactive</option><option value="active">active</option><option value="past_due">past due</option><option value="canceled">canceled</option></select></td><td><input type="date" defaultValue={row.subscriptionExpiresAt ? String(row.subscriptionExpiresAt).slice(0, 10) : ""} onChange={(event) => { row.subscriptionExpiresAt = event.target.value ? new Date(`${event.target.value}T23:59:59Z`).toISOString() : null; }} /></td><td><button type="button" onClick={() => void save(row)}>Save</button></td></tr>)}</tbody></table></div>; }
function DataTable({ rows }: { rows: Array<Record<string, unknown>> }) { if (!rows.length) return <p className="admin-empty">No records yet.</p>; const columns = Object.keys(rows[0]); return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? row.scopeKey ?? index)}>{columns.map((column) => <td key={column}>{formatValue(row[column], column)}</td>)}</tr>)}</tbody></table></div>; }

export default function AdminPage() {
  const [metrics, setMetrics] = useState<Metrics | null>(null); const [lists, setLists] = useState<Lists | null>(null); const [email, setEmail] = useState(""); const [filter, setFilter] = useState<Filter>("users"); const [error, setError] = useState(""); const [checking, setChecking] = useState(true);
  const load = async () => { try { const response = await fetch("/api/admin", { cache: "no-store" }); const data = await response.json(); if (response.ok) { setMetrics(data.metrics); setLists(data.lists); setEmail(data.user.email); } else setError(data.error ?? "Admin authentication required."); } finally { setChecking(false); } };
  useEffect(() => { void load(); }, []);
  const selectedRows = useMemo(() => lists?.[filter] ?? [], [lists, filter]);
  const saveUser = async (row: Record<string, unknown>) => { const response = await fetch("/api/admin", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "updateUser", userId: row.id, role: row.role, plan: row.plan, subscriptionStatus: row.subscriptionStatus, subscriptionExpiresAt: row.subscriptionExpiresAt ?? null }) }); if (!response.ok) { const data = await response.json(); setError(data.error ?? "Unable to save user."); return; } await load(); };
  if (checking) return <main className="admin-loading"><div className="stamp">HONTO?!</div><p>Opening your dashboard…</p><div className="admin-loading-dots"><i/><i/><i/></div></main>;
  if (!metrics || !lists) return <main className="admin-page admin-login"><div className="stamp">HONTO?!</div><h1>Admin access required</h1><p>{error || "Sign in with your admin Google account to continue."}</p><a className="admin-back" href="/">← Back to Honto</a></main>;
  return <main className="admin-page"><header className="admin-header"><div><p>Signed in as {email}</p><h1>Honto admin</h1></div><a className="admin-back" href="/">← Back to Honto</a></header><section className="admin-metrics">{(Object.keys(metrics) as Filter[]).map((key) => <button type="button" key={key} className={`admin-metric ${filter === key ? "selected" : ""}`} onClick={() => setFilter(key)}><small>{labels[key]}</small><strong>{key === "aiEstimatedCostUsd" ? `$${metrics[key]}` : metrics[key]}</strong><span>{key === "aiEstimatedCostUsd" ? "Estimated, not final billing" : "View list →"}</span></button>)}</section><section className="admin-list">{error && <p className="form-error">{error}</p>}<div className="admin-list-heading"><h2>{labels[filter]}</h2><span>{selectedRows.length} shown</span></div>{filter === "users" ? <UserTable rows={selectedRows} save={saveUser}/> : filter === "aiEstimatedCostUsd" ? <p className="admin-empty">This is an estimate based on $0.002 per generation. Configure actual billing tracking later.</p> : <DataTable rows={selectedRows}/>}</section></main>;
}
