export const themeCategories = {
  mixed: [
    "a time you surprised yourself", "something you learned by accident", "a decision you made on a whim", "a time you misunderstood someone", "a purchase you still use", "a rule you secretly ignore", "a promise you managed to keep", "a small risk you took", "a time you changed your mind", "a moment you felt out of place", "a skill you taught yourself", "a time you helped a stranger", "a habit your friends tease you about", "a time technology failed you", "a place you got completely lost", "a meal you learned to make", "a time you were unexpectedly lucky", "something you regret buying", "a compliment you still remember", "a plan that went very differently",
  ],
  family: [
    "a story your family tells about you", "a tradition you would keep forever", "a school memory your family remembers", "a trip that changed your family", "a recipe someone taught you", "a rule from your childhood home", "a pet that shaped your family", "a holiday that went sideways", "a phrase someone in your family always says", "a family argument you can laugh about now", "a chore you tried to avoid", "an inside joke from home", "a relative who inspired you", "a family celebration you remember clearly", "a hand me down you actually loved", "a childhood fear your family knew about", "a road trip your family still discusses", "a nickname you had at home", "a lesson you learned from a relative", "a time your family surprised you",
  ],
  innocent: [
    "a silly mistake you made at school", "the strangest snack you have tried", "a cartoon you watched on repeat", "a harmless prank you pulled", "a nickname you had as a kid", "a funny school memory", "a rainy day you remember", "a game you always wanted to win", "a weird food combination you enjoy", "a small fear you eventually got over", "a song you know by heart", "a typo that caused confusion", "a talent show or school performance", "a gift you still remember receiving", "a smell that takes you back", "a minor embarrassment you can laugh about", "a routine that always cheers you up", "a toy or game you loved", "a time you got away with something harmless", "a hobby you picked up for a funny reason",
  ],
  life: [
    "a subject you loved or hated at school", "your first job and what it taught you", "a trip that changed how you think", "a big decision you made too quickly", "a lesson you learned later than most", "a project you are proud you finished", "a difficult conversation you are glad you had", "a hobby you tried and abandoned", "a place you could imagine living", "a milestone you celebrated quietly", "a goodbye that stayed with you", "a risk that worked out", "a plan for the next few years", "a skill you want to learn", "a time you had to start over", "an opportunity you almost missed", "a choice you would make differently", "your idea of a perfect ordinary day", "a promise you made to yourself", "a childhood dream you still think about",
  ],
  spicy: [
    "a crush you never told about", "your most awkward first date", "a flirtation that went wrong", "a celebrity you genuinely fancied", "a dating app conversation you remember", "a romantic gesture you planned", "a kiss that surprised you", "a bold message you actually sent", "a green flag you noticed quickly", "a red flag you ignored", "a romance that almost happened", "a misunderstanding with someone you liked", "a date you would happily repeat", "a dealbreaker you discovered the hard way", "a school age crush you remember", "a romantic plot twist in your life", "a moment you felt jealous", "a love song that fits your story", "a dating disaster you can laugh about", "your idea of a great date",
  ],
  wild: [
    "a party that became much more chaotic", "the strangest dare you accepted", "a night you planned badly", "a harmless theory you believed for a while", "a spontaneous trip you took", "a rule you broke and survived", "a fashion choice you regret", "a terrible idea that somehow worked", "a story people doubt is true", "a time you completely lost the plot", "a coincidence you still cannot explain", "a message from a stranger", "a time you had to improvise", "an encounter you could not have predicted", "an accidental adventure", "a secret nickname or alter ego", "a misunderstanding that escalated", "something you did on a bet", "a story you will tell years from now", "the most chaotic friend you have had",
  ],
} as const;
