const themeCategories = { mixed: ["a tiny victory", "your most-used emoji", "a strange coincidence", "a bad haircut", "a lucky escape", "a comfort food", "a childhood nickname", "a hidden talent", "a memorable purchase", "a song you secretly love", "a weird habit", "an awkward elevator ride", "a time you got lost", "a surprising compliment", "a weekend ritual", "a questionable fashion choice", "a random act of kindness", "a silly argument", "a thing you collect", "a moment you felt brave"], family: ["a family tradition", "a grandparent's story", "your first family trip", "a sibling rivalry", "a family recipe", "a childhood rule", "a family pet", "a holiday memory", "a relative's catchphrase", "your family superpower", "a family celebration", "a chore you hated", "a family inside joke", "your first school day", "a family heirloom", "a funny parent moment", "a childhood fear", "a family road trip", "a nickname at home", "a lesson from a relative"], innocent: ["a silly mistake", "your favorite snack", "a tiny superstition", "a cartoon you loved", "a funny school memory", "a harmless prank", "a silly nickname", "a rainy-day activity", "a game-night habit", "a weird food combo", "a small fear", "a lucky number", "a song you know by heart", "a funny typo", "a talent show moment", "a gift you remember", "a favorite smell", "a minor embarrassment", "a cozy routine", "a thing that always cheers you up"], life: ["your first job", "a trip that changed you", "a big life decision", "a goal you abandoned", "a lesson learned late", "your proudest project", "a brave conversation", "a hobby you tried", "a place you want to live", "a personal milestone", "a difficult goodbye", "a risk that paid off", "a plan for the future", "a skill you want next", "a time you reinvented yourself", "an unexpected opportunity", "a choice you would redo", "your perfect day", "a promise you made", "a dream from childhood"], spicy: ["a memorable crush", "your worst first date", "a flirt gone wrong", "a celebrity crush", "a dating app story", "a secret romantic gesture", "a kiss you remember", "your boldest DM", "a relationship green flag", "a relationship red flag", "an almost-romance", "a romantic misunderstanding", "a date you would repeat", "a dating dealbreaker", "a crush from school", "a romantic plot twist", "a jealousy moment", "a love song that fits you", "a dating disaster", "your ideal date"], wild: ["a party that got chaotic", "a ridiculous dare", "a night you barely planned", "a harmless conspiracy", "a spontaneous trip", "a rule you broke", "a risky fashion choice", "a terrible idea that worked", "a story nobody believes", "a moment you lost control", "a bizarre coincidence", "a mysterious message", "a time you improvised", "a strange encounter", "an accidental adventure", "a secret alter ego", "a wild misunderstanding", "a thing you did on a bet", "a story for future you", "your most chaotic friend"] } as const;

const fallbackTheme = (categories: string | string[] = "safe", exclude: string[] = []) => { const requested = Array.isArray(categories) ? categories : categories.split(","); const keys = requested.filter((key): key is keyof typeof themeCategories => key in themeCategories); const safeKeys: (keyof typeof themeCategories)[] = keys.length ? keys : ["mixed", "family", "innocent", "life"]; const list = safeKeys.flatMap((key) => themeCategories[key]); const available = list.filter((item) => !exclude.includes(item)); return available[Math.floor(Math.random() * Math.max(available.length, 1))] ?? list[0]; };
const fallbackLies = (truth: string) => [`I once told someone I was ${truth.toLowerCase().slice(0, 48)}.`, `I have a photo proving that ${truth.toLowerCase().slice(0, 42)}.`, `My oldest friend still thinks ${truth.toLowerCase().slice(0, 40)}.`, `I learned the hard way that ${truth.toLowerCase().slice(0, 38)}.`, `I secretly wish people knew that ${truth.toLowerCase().slice(0, 34)}.`];

export default async function handler(req: any, res: any) {
  const body = (req.body ?? {}) as { kind?: "theme" | "lies"; truth?: string; prompt?: string; category?: string | string[]; exclude?: string[] };
  const categories = Array.isArray(body.category) ? body.category.filter((key): key is keyof typeof themeCategories => key in themeCategories) : (body.category ?? "safe");
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey.startsWith("REPLACE_")) return body.kind === "lies" ? res.status(200).json({ lies: fallbackLies(body.truth ?? "my secret"), source: "fallback" }) : res.status(200).json({ prompt: fallbackTheme(categories, body.exclude), source: "fallback" });
  try {
    const instruction = body.kind === "lies" ? `Write five believable but clearly fictional alternative statements for a party game. The player's true statement is: "${(body.truth ?? "").slice(0, 180)}". Theme: ${(body.prompt ?? "anything goes").slice(0, 80)}. Return five short English statements as a JSON object with a lies array. Keep them safe, playful, non-defamatory, and non-explicit.` : `Give one fresh, playful English theme for a two-lies-one-truth party game in the ${(Array.isArray(categories) ? categories.join(", ") : categories)} categories. Avoid: ${(body.exclude ?? []).join(", ") || "none"}. Return only a 2–8 word noun phrase.`;
    const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-5.4-nano", store: false, input: instruction, text: { format: body.kind === "lies" ? { type: "json_schema", name: "lie_options", strict: true, schema: { type: "object", properties: { lies: { type: "array", items: { type: "string" }, minItems: 5, maxItems: 5 } }, required: ["lies"], additionalProperties: false } } : { type: "text" } }, max_output_tokens: body.kind === "lies" ? 260 : 30 }) });
    if (!response.ok) throw new Error("OpenAI request failed");
    const data = await response.json() as { output_text?: string };
    if (body.kind === "lies") { const parsed = JSON.parse(data.output_text ?? "{}"); const lies = Array.isArray(parsed.lies) ? parsed.lies.filter((item: unknown): item is string => typeof item === "string").map((item: string) => item.trim().slice(0, 180)).filter(Boolean).slice(0, 5) : []; if (lies.length === 5) return res.status(200).json({ lies, source: "ai" }); throw new Error("Invalid lie options"); }
    const prompt = data.output_text?.trim().replace(/[.!?]+$/, "").slice(0, 100); if (!prompt) throw new Error("Invalid theme"); return res.status(200).json({ prompt, source: "ai" });
  } catch { return body.kind === "lies" ? res.status(200).json({ lies: fallbackLies(body.truth ?? "my secret"), source: "fallback" }) : res.status(200).json({ prompt: fallbackTheme(categories, body.exclude), source: "fallback" }); }
}
