const themeCategories = { mixed: ["a tiny victory", "your most-used emoji", "a strange coincidence", "a bad haircut", "a lucky escape", "a comfort food", "a childhood nickname", "a hidden talent", "a memorable purchase", "a song you secretly love", "a weird habit", "an awkward elevator ride", "a time you got lost", "a surprising compliment", "a weekend ritual", "a questionable fashion choice", "a random act of kindness", "a silly argument", "a thing you collect", "a moment you felt brave"], family: ["a family tradition", "a grandparent's story", "your first family trip", "a sibling rivalry", "a family recipe", "a childhood rule", "a family pet", "a holiday memory", "a relative's catchphrase", "your family superpower", "a family celebration", "a chore you hated", "a family inside joke", "your first school day", "a family heirloom", "a funny parent moment", "a childhood fear", "a family road trip", "a nickname at home", "a lesson from a relative"], innocent: ["a silly mistake", "your favorite snack", "a tiny superstition", "a cartoon you loved", "a funny school memory", "a harmless prank", "a silly nickname", "a rainy-day activity", "a game-night habit", "a weird food combo", "a small fear", "a lucky number", "a song you know by heart", "a funny typo", "a talent show moment", "a gift you remember", "a favorite smell", "a minor embarrassment", "a cozy routine", "a thing that always cheers you up"], life: ["your first job", "a trip that changed you", "a big life decision", "a goal you abandoned", "a lesson learned late", "your proudest project", "a brave conversation", "a hobby you tried", "a place you want to live", "a personal milestone", "a difficult goodbye", "a risk that paid off", "a plan for the future", "a skill you want next", "a time you reinvented yourself", "an unexpected opportunity", "a choice you would redo", "your perfect day", "a promise you made", "a dream from childhood"], spicy: ["a memorable crush", "your worst first date", "a flirt gone wrong", "a celebrity crush", "a dating app story", "a secret romantic gesture", "a kiss you remember", "your boldest DM", "a relationship green flag", "a relationship red flag", "an almost-romance", "a romantic misunderstanding", "a date you would repeat", "a dating dealbreaker", "a crush from school", "a romantic plot twist", "a jealousy moment", "a love song that fits you", "a dating disaster", "your ideal date"], wild: ["a party that got chaotic", "a ridiculous dare", "a night you barely planned", "a harmless conspiracy", "a spontaneous trip", "a rule you broke", "a risky fashion choice", "a terrible idea that worked", "a story nobody believes", "a moment you lost control", "a bizarre coincidence", "a mysterious message", "a time you improvised", "a strange encounter", "an accidental adventure", "a secret alter ego", "a wild misunderstanding", "a thing you did on a bet", "a story for future you", "your most chaotic friend"] } as const;

const fallbackTheme = (categories: string | string[] = "safe", exclude: string[] = []) => { const requested = Array.isArray(categories) ? categories : categories.split(","); const keys = requested.filter((key): key is keyof typeof themeCategories => key in themeCategories); const safeKeys: (keyof typeof themeCategories)[] = keys.length ? keys : ["mixed", "family", "innocent", "life"]; const list = safeKeys.flatMap((key) => themeCategories[key]); const available = list.filter((item) => !exclude.includes(item)); return available[Math.floor(Math.random() * Math.max(available.length, 1))] ?? list[0]; };
const fallbackLies = (truth: string) => [`I once told someone I was ${truth.toLowerCase().slice(0, 48)}.`, `I have a photo proving that ${truth.toLowerCase().slice(0, 42)}.`, `My oldest friend still thinks ${truth.toLowerCase().slice(0, 40)}.`, `I learned the hard way that ${truth.toLowerCase().slice(0, 38)}.`, `I secretly wish people knew that ${truth.toLowerCase().slice(0, 34)}.`];
const responseText = (data: { output_text?: string; output?: Array<{ content?: Array<{ text?: string }> }> }) => data.output_text ?? data.output?.flatMap((item) => item.content ?? []).map((item) => item.text ?? "").join("") ?? "";
const normalizeTheme = (value: string) => value.trim().replace(/^["'“”‘’]+|["'“”‘’]+$/g, "").replace(/[.!?]+$/g, "").replace(/\s+/g, " ");
const usableTheme = (value: string, exclude: string[] = []) => { const theme = normalizeTheme(value); const words = theme.split(" ").filter(Boolean); return words.length >= 3 && words.length <= 8 && !/[—–\-:;|]/.test(theme) && !/\b(i|my|me|we|our|us)\b/i.test(theme) && !/\b(when|the time|a time)\s+(i|my|we|our)\b/i.test(theme) && !/\b(edition|confession|confessions|category|categories|theme|party game|two lies|one truth|your relatives|family tradition)$\b/i.test(theme) && !/\b(spicy sausage|chemistry class).*(spicy sausage|chemistry class)\b/i.test(theme) && !exclude.some((item) => item.toLowerCase() === theme.toLowerCase()) ? theme : null; };
const categoryGuidance = (categories: string | string[]) => { const key = Array.isArray(categories) ? categories[0] : categories; if (key === "spicy") return "This is an adults only 18+ category for consenting adults. Topics may openly discuss sex, sexual experiences, desire, intimacy, and bedroom communication, but never minors, coercion, exploitation, incest, or violence. Keep each topic non graphic and suitable as a conversation prompt."; if (key === "flirty") return "Keep this flirty but not explicit: dating, attraction, crushes, romance, kissing, relationship choices, and playful adult tension. Do not turn it into food, school science, or unrelated shock humor."; if (key === "family") return "Keep every topic about a family relationship, home tradition, relative, or shared family memory."; if (key === "innocent") return "Keep every topic light, wholesome, and suitable for mixed ages, focused on school, hobbies, food, memories, and harmless mistakes."; return "Keep every topic grounded in one ordinary personal situation from this category, with no unrelated mashups."; };

export default async function handler(req: any, res: any) {
  const body = (req.body ?? {}) as { kind?: "theme" | "lies"; truth?: string; prompt?: string; category?: string | string[]; exclude?: string[]; fresh?: boolean; customTheme?: string; count?: number };
  const categories = Array.isArray(body.category) ? body.category.filter((key): key is keyof typeof themeCategories => key in themeCategories) : (body.category ?? "safe");
  const count = Number.isInteger(body.count) ? Math.max(3, Math.min(20, body.count as number)) : 3;
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey.startsWith("REPLACE_")) return body.kind === "lies" ? res.status(200).json({ lies: fallbackLies(body.truth ?? "my secret"), source: "fallback" }) : res.status(200).json({ prompt: fallbackTheme(categories, body.exclude), source: "fallback" });
  try {
    const instruction = body.kind === "lies"
      ? `You are helping me play Two Lies and One Truth. My truth is: "${(body.truth ?? "").slice(0, 180)}". Theme: ${(body.prompt ?? "anything goes").slice(0, 80)}. Write five completely different possible lies in natural English. Use the truth ONLY to match its approximate character length and the user's writing style, including casual wording, grammar mistakes, spelling, missing accents, capitalization, and punctuation. Do not reuse the truth's actual event, people, place, app, date, action, or outcome. Do not keep the truth and add details. Do not rewrite it with synonyms. Do not repeat any sequence of four words from it and do not start with the same words. Each lie must be a separate believable story that could confuse a friend, using a different event or situation while staying loosely within the broad theme. For example, if the truth says someone went out with a guy from a language app, do not mention that same date or language app in any lie. Use unrelated alternatives such as a different person, a different place, or a different kind of day. Return exactly five statements in a JSON object with a lies array. Do not use quotation marks, em dashes, en dashes, or hyphens.`
      : `Create ${count} natural English topic phrases for a two-lies-one-truth game. Every phrase must describe one clear, relatable personal situation that a player can understand immediately and answer with a real story. Use only this subject area: ${(Array.isArray(categories) ? categories.join(", ") : categories)}. ${categoryGuidance(categories)} Custom subject: ${(body.customTheme ?? "").slice(0, 80) || "none"}. ${body.customTheme ? "Make every option specifically about the custom subject." : ""} ${body.fresh ? "Make these fresh and specific, not generic." : ""} Good examples: a time you got in trouble at school, a family tradition you still follow, a teacher you will never forget, a first job mistake, a trip that changed your mind. Bad examples: family tradition, your relatives, random combinations like spicy sausage in chemistry class, or a food and school mashup when the subject does not ask for both. Never combine unrelated objects, places, or categories. Do not write a title, question, instruction, or generic label. Use plain conversational lowercase wording with 5 to 12 words each. No punctuation, quotes, colon, semicolon, question mark, exclamation mark, em dash, en dash, or hyphen. Do not use words such as edition, confession, category, theme, or party game. Avoid: ${(body.exclude ?? []).join(", ") || "none"}. Return a JSON object with a themes array containing exactly ${count} options.`;
    const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: process.env.OPENAI_MODEL ?? "gpt-5.4-nano", store: false, input: instruction, text: { format: { type: "json_schema", name: body.kind === "lies" ? "lie_options" : "theme_options", strict: true, schema: body.kind === "lies" ? { type: "object", properties: { lies: { type: "array", items: { type: "string" }, minItems: 5, maxItems: 5 } }, required: ["lies"], additionalProperties: false } : { type: "object", properties: { themes: { type: "array", items: { type: "string" }, minItems: count, maxItems: count } }, required: ["themes"], additionalProperties: false } } }, max_output_tokens: body.kind === "lies" ? 260 : Math.max(180, count * 35) }) });
    if (!response.ok) { const detail = await response.text(); console.error("[suggest] OpenAI request failed", { status: response.status, model: process.env.OPENAI_MODEL ?? "gpt-5.4-nano", detail: detail.slice(0, 500) }); throw new Error(`OpenAI request failed (${response.status})`); }
    const data = await response.json() as { output_text?: string; output?: Array<{ content?: Array<{ text?: string }> }> };
    const text = responseText(data);
    if (body.kind === "lies") { const parsed = JSON.parse(text || "{}"); const lies = Array.isArray(parsed.lies) ? parsed.lies.filter((item: unknown): item is string => typeof item === "string").map((item: string) => item.trim().slice(0, 180)).filter(Boolean).slice(0, 5) : []; if (lies.length === 5) return res.status(200).json({ lies, source: "ai" }); throw new Error("Invalid lie options"); }
    const parsed = JSON.parse(text || "{}"); const prompts = Array.isArray(parsed.themes) ? parsed.themes.map((item: unknown) => typeof item === "string" ? usableTheme(item, body.exclude) : null).filter((item: string | null): item is string => Boolean(item)).map((item: string) => item.slice(0, 100)).slice(0, count) : []; if (!prompts.length) throw new Error("Invalid theme"); return res.status(200).json({ prompt: prompts[0], prompts, source: "ai" });
  } catch (error) { console.error("[suggest] Returning fallback", { kind: body.kind ?? "theme", hasKey: Boolean(apiKey), placeholder: Boolean(apiKey?.startsWith("REPLACE_")), model: process.env.OPENAI_MODEL ?? "gpt-5.4-nano", error: error instanceof Error ? error.message : String(error) }); return body.kind === "lies" ? res.status(200).json({ lies: fallbackLies(body.truth ?? "my secret"), source: "fallback" }) : res.status(200).json({ prompt: fallbackTheme(categories, body.exclude), source: "fallback" }); }
}
